#!/bin/bash
#
# Horus Eye
# Copyright (C) 2010  USPGameDev
#
# game/update_cmake
# Gera o arquivo de configuracao do CMake. Rode
# este script antes do CMake.
#

make clean

if [ "$1" = "--editor" ]; then
  EDITOR=1
  echo "Configurando editor..."
else
  EDITOR=0
  echo "Configurando game..."
fi

if [ -e ./CMakeLists.base ]; then
  FILES=`find . ../framework | grep "^.*\.\(h\|cc\)$"`
  echo -n "SET(GAME_SRCS " > ./CMakeLists.txt
  for f in $FILES; do

    if [ "$EDITOR" = "1" ]; then
      if [ "$f" != "./main.cc" ]; then
        echo -n "$f " >> ./CMakeLists.txt
      fi
    else
      if [ "$f" != "./editor.cc" ]; then
        echo -n "$f " >> ./CMakeLists.txt
      fi
    fi

  done
  echo ")" >> ./CMakeLists.txt
  cat ./CMakeLists.base >> ./CMakeLists.txt
  echo "Arquivo ./CMakeLists.txt atualizado com sucesso."
else
  echo "Erro: arquivo ./CmakeLists.base nao encontrado!"
fi
