install:
  - sudo apt-get install cmake libsdl1.2-dev libsdl-image1.2 libsdl-mixer1.2-dev libsdl-ttf2.0-0 swig2.0 lua5.1 python2.6
  - wget http://uspgamedev.org/downloads/projects/ugdk/v0.4.0/libugdk_0.4.0_squeeze_i386.deb
  - sudo dpkg -i libugdk_0.4.0_squeeze_i386.deb

script:
  - cmake .
  - make horus_eye

notifications:
  email:
      - travis@uspgamedev.org