install:
  - sudo apt-get install libsdl-image1.2 libsdl-mixer1.2 libsdl-mixer1.2-dev libsdl-ttf2.0-0 libsdl1.2-dev libsdl1.2debian libsdl1.2debian-alsa libslang2-dev lua5.1  python2.6  python2.6-minimal
  - wget http://uspgamedev.org/downloads/projects/ugdk/v0.4.0/libugdk_0.4.0_squeeze_i386.deb
  - sudo gdebi libugdk_0.4.0_squeeze_i386.deb

script:
  - cmake .
  - make horus_eye

notifications:
  email:
    - henrique@uspgamedev.org