install:
  - sudo apt-get install cmake libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev swig2.0 liblua5.1-0-dev python-dev

script:
  - cmake .
  - make horus_eye

notifications:
  email:
    - henrique@uspgamedev.org