install:
  - wget http://uspgamedev.org/downloads/projects/ugdk/v0.4.0/libugdk_0.4.0_squeeze_i386.deb
  - sudo gdebi libugdk_0.4.0_squeeze_i386.deb

script:
  - cmake .
  - make horus_eye

notifications:
  email:
      - travis@uspgamedev.org