language: cpp

install:
  - sudo apt-get install cmake libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev swig2.0 lua5.1 liblua5.1-0-dev python-dev

script:
  - cmake . -DHORUSEYE_INTERNAL_UGDK=On
  - make horus_eye

notifications:
  email:
    - travis@uspgamedev.org