language: cpp

install:
  - sudo apt-get update
  - sudo apt-get install cmake libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev swig2.0 lua5.1 liblua5.1-0-dev python-dev
  - sudo apt-get install emacsen-common
  - wget http://uspgamedev.org/downloads/libs/ubuntu/cmake_2.8.11.2-1ubuntu5_amd64.deb http://uspgamedev.org/downloads/libs/ubuntu/cmake-data_2.8.11.2-1ubuntu5_all.deb
  - sudo dpkg -i cmake_*.deb cmake-data_*.deb

compiler:
  - gcc
  - clang

script:
  - cmake . -DHORUSEYE_INTERNAL_UGDK=On
  - make horus_eye

notifications:
  email:
    - travis@uspgamedev.org
