#!/bin/bash
#
# Horus Eye
# Copyright (C) 2010  USPGameDev
#
# sandbox/ZIndexTest/update_cmake
# Gera o arquivo de configuracao do CMake. Rode
# este script antes do CMake.
#

if [ -e ./CMakeLists.base ]; then
  FILES=`find . ../../framework ../../game | grep "^.*\.\(h\|cc\)$" | grep -v "main.cc"`
  echo -n "SET(GAME_SRCS " > ./CMakeLists.txt
  for f in $FILES; do
    echo -n "$f " >> ./CMakeLists.txt
  done
  echo ")" >> ./CMakeLists.txt
  cat ./CMakeLists.base >> ./CMakeLists.txt
  echo "Arquivo ./CMakeLists.txt atualizado com sucesso."
else
  echo "Erro: arquivo ./CmakeLists.base nao encontrado!"
fi
