SET(GAME_SRCS 
    ./editor/layers/mapspriteslayer.cc 
    ./editor/layers/mapspriteslayer.h 
    ./editor/layers/maptileslayer.cc 
    ./editor/layers/maptileslayer.h 
    ./editor/mapeditor.cc 
    ./editor/mapeditor.h 
    ./editor/mapobject.cc 
    ./editor/mapobject.h 
    ./editor/scenes/editormenu.cc 
    ./editor/scenes/editormenu.h 
    ./externals/inifile.cc 
    ./externals/inifile.h 
    ./game/builders/conditionbuilder.cc 
    ./game/builders/conditionbuilder.h 
    ./game/builders/doodadbuilder.cc 
    ./game/builders/doodadbuilder.h 
    ./game/builders/entitybuilder.cc 
    ./game/builders/entitybuilder.h 
    ./game/builders/explosionbuilder.cc 
    ./game/builders/explosionbuilder.h 
    ./game/builders/functions/carrier.cc 
    ./game/builders/functions/carrier.h 
    ./game/builders/goodmenubuilder.cc 
    ./game/builders/goodmenubuilder.h 
    ./game/builders/herobuilder.cc 
    ./game/builders/herobuilder.h 
    ./game/builders/itembuilder.cc 
    ./game/builders/itembuilder.h 
    ./game/builders/mummybuilder.cc 
    ./game/builders/mummybuilder.h 
    ./game/builders/projectilebuilder.cc 
    ./game/builders/projectilebuilder.h 
    ./game/builders/scriptbuilder.cc 
    ./game/builders/scriptbuilder.h 
    ./game/builders/taskbuilder.cc 
    ./game/builders/taskbuilder.h 
    ./game/components.h 
    ./game/components/animation.cc 
    ./game/components/animation.h 
    ./game/components/caster.cc 
    ./game/components/caster.h 
    ./game/components/controller.h 
    ./game/components/damageable.cc 
    ./game/components/damageable.h 
    ./game/components/direction.cc 
    ./game/components/direction.h 
    ./game/components/graphic.cc 
    ./game/components/graphic.h 
    ./game/components/logic.h 
    ./game/components/logic/creature.cc 
    ./game/components/logic/creature.h 
    ./game/components/logic/follower.cc 
    ./game/components/logic/follower.h 
    ./game/components/logic/hero.cc 
    ./game/components/logic/hero.h 
    ./game/components/logic/wall.cc 
    ./game/components/logic/wall.h 
    ./game/components/mummycontroller.cc 
    ./game/components/mummycontroller.h 
    ./game/components/playercontroller.cc 
    ./game/components/playercontroller.h 
    ./game/components/projectile.h 
    ./game/config.h 
    ./game/context.cc 
    ./game/context.h 
    ./game/entities/emitterentity.h 
    ./game/entities/sandstormemitter.cc 
    ./game/entities/sandstormemitter.h 
    ./game/initializer.cc 
    ./game/initializer.h 
    ./game/main.cc 
    ./game/modules.cc 
    ./game/modules.h 
    ./game/resources/capacityblocks.h 
    ./game/resources/containedresource.h 
    ./game/resources/countableresource.h 
    ./game/resources/energy.h 
    ./game/resources/resource.h 
    ./game/scenes.h 
    ./game/scenes/gamelayer.h 
    ./game/scenes/imagescene.cc 
    ./game/scenes/imagescene.h 
    ./game/scenes/loading.cc 
    ./game/scenes/loading.h 
    ./game/scenes/menu.cc 
    ./game/scenes/menu.h 
    ./game/scenes/menuhandler.h 
    ./game/scenes/scrollingimagescene.cc 
    ./game/scenes/scrollingimagescene.h 
    ./game/scenes/world.cc 
    ./game/scenes/world.h 
    ./game/skills.h 
    ./game/skills/combatart.h 
    ./game/skills/divinegift.h 
    ./game/skills/herobaseweapon.cc 
    ./game/skills/herobaseweapon.h 
    ./game/skills/heroexplosionweapon.cc 
    ./game/skills/heroexplosionweapon.h 
    ./game/skills/herofireballweapon.cc 
    ./game/skills/herofireballweapon.h 
    ./game/skills/herolightningweapon.cc 
    ./game/skills/herolightningweapon.h 
    ./game/skills/herolightweapon.cc 
    ./game/skills/herolightweapon.h 
    ./game/skills/herometeorweapon.cc 
    ./game/skills/herometeorweapon.h 
    ./game/skills/mummyrangedweapon.cc 
    ./game/skills/mummyrangedweapon.h 
    ./game/skills/mummyweapon.cc 
    ./game/skills/mummyweapon.h 
    ./game/skills/papermummyweapon.cc 
    ./game/skills/papermummyweapon.h 
    ./game/skills/pharaohrangedweapon.cc 
    ./game/skills/pharaohrangedweapon.h 
    ./game/skills/pharaohsummonweapon.cc 
    ./game/skills/pharaohsummonweapon.h 
    ./game/skills/sandstorm.cc 
    ./game/skills/sandstorm.h 
    ./game/skills/skill.h 
    ./game/skills/usearguments.h 
    ./game/sprites.h 
    ./game/sprites/condition.h 
    ./game/sprites/itemevent.h 
    ./game/sprites/worldobject.cc 
    ./game/sprites/worldobject.h 
    ./game/utils/constants.cc 
    ./game/utils/constants.h 
    ./game/utils/geometryprimitives.cc 
    ./game/utils/geometryprimitives.h 
    ./game/utils/hud.cc 
    ./game/utils/hud.h 
    ./game/utils/hudimagefactory.cc 
    ./game/utils/hudimagefactory.h 
    ./game/utils/imagefactory.cc 
    ./game/utils/imagefactory.h 
    ./game/utils/isometricanimationset.cc 
    ./game/utils/isometricanimationset.h 
    ./game/utils/levelloader.cc 
    ./game/utils/levelloader.h 
    ./game/utils/levelmanager.cc 
    ./game/utils/levelmanager.h 
    ./game/utils/menuimagefactory.cc 
    ./game/utils/menuimagefactory.h 
    ./game/utils/settings.cc 
    ./game/utils/settings.h 
    ./game/utils/tile.cc 
    ./game/utils/tile.h 
    ./game/utils/tilefwd.h 
    ./game/utils/visionstrategy.cc 
    ./game/utils/visionstrategy.h 
    ./mac/SDLMain.h 
    ./module/builderLUA_wrap.cc 
    ./module/builderPYTHON_wrap.cc 
    ./module/component/logicproxy.h 
    ./module/componentLUA_wrap.cc 
    ./module/componentPYTHON_wrap.cc 
    ./module/contextLUA_wrap.cc 
    ./module/contextPYTHON_wrap.cc 
    ./module/luaproxy.h 
)
